// Master Dataset constructed exactly from Bits_SW.pdf and bits HW.pdf
export const problemStatements = [
  // ==========================================
  // --- SOFTWARE TRACK (26 PROBLEMS SERIALIZED 1 to 26) ---
  // ==========================================
  {
    serialNo: 1,
    id: "PS1",
    origId: "PS1",
    title: "Real-Time Network Intrusion Dashboard",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Security",
    difficulty: "EASY",
    overview: "Watch live network traffic, catch attacks using machine learning, and show alerts on a dashboard.",
    fullDetails: "Security teams need a way to spot malicious activity on a network as it happens rather than after the damage is done. This project involves continuously capturing live network traffic, applying a machine-learning model to classify normal versus attack patterns, and surfacing detected threats in real time on a monitoring dashboard so operators can respond immediately."
  },
  {
    serialNo: 2,
    id: "PS2",
    origId: "PS69",
    title: "CareSync",
    track: "software",
    isHybrid: false,
    category: "AI & HealthTech",
    difficulty: "MEDIUM",
    overview: "A lightweight AI triage tool for clinics with poor internet connectivity and limited resources.",
    fullDetails: "Many clinics, especially in remote or under-resourced areas, lack reliable internet access and sufficient staff to triage incoming patients efficiently. CareSync is a lightweight AI-driven triage tool designed to run with minimal connectivity and hardware requirements, helping clinic staff quickly assess patient urgency and prioritize care using whatever limited data and infrastructure is available."
  },
  {
    serialNo: 3,
    id: "PS3",
    origId: "PS10",
    title: "SIM Swap and Suspicious Call Pattern Detection",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Telecom Security",
    difficulty: "MEDIUM",
    overview: "Detects fraudulent SIM swaps and suspicious call patterns using machine learning.",
    fullDetails: "SIM swap fraud allows attackers to hijack a victim's phone number and bypass SMS-based authentication, while unusual call patterns can indicate scams or account takeovers. This project requires building a machine-learning system that analyzes SIM change events and call metadata to flag fraudulent SIM swaps and suspicious calling behavior in near real time."
  },
  {
    serialNo: 4,
    id: "PS4",
    origId: "PS20",
    title: "5G Network Security Misconfiguration Scanner",
    track: "software",
    isHybrid: false,
    category: "Wireless & Network Security",
    difficulty: "MEDIUM",
    overview: "Scans a simulated 5G network setup for common security misconfigurations.",
    fullDetails: "5G network deployments are complex, and misconfigured settings can leave gaps that attackers exploit. This project requires building a scanner that inspects a simulated 5G network setup against a checklist of known misconfiguration patterns (open ports, weak authentication settings, default credentials, insecure protocol configurations, etc.) and reports the issues it finds."
  },
  {
    serialNo: 5,
    id: "PS5",
    origId: "PS59",
    title: "CommShield",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Zero-Day Security",
    difficulty: "HARD",
    overview: "An AI system that learns normal 5G/6G network behavior to catch brand-new (zero-day) attacks.",
    fullDetails: "Signature-based detection cannot catch attacks that have never been seen before. CommShield addresses this by learning a baseline of normal 5G/6G network behavior and flagging deviations from that baseline as potential zero-day threats, allowing previously unknown attack patterns to be detected without relying on a known-attack database."
  },
  {
    serialNo: 6,
    id: "PS6",
    origId: "PS9",
    title: "Deadline-Aware Cloud Task Continuity",
    track: "software",
    isHybrid: false,
    category: "Cloud Systems & Networking",
    difficulty: "MEDIUM",
    overview: "Develop a system that predicts network degradation ahead of time and protects the progress of a time-critical cloud task so its most important data reaches the destination before the connection worsens further.",
    fullDetails: "Time-critical cloud tasks — emergency evidence uploads, field-report syncs, inspection data — often begin under stable connectivity but fail mid-way when the network degrades, forcing a full restart. This project requires continuously monitoring latency, jitter, packet loss, uplink speed, remaining task size, and deadline, and when failure is predicted, taking preemptive action such as prioritizing critical data, checkpointing progress, compressing/dividing the remaining transfer, or switching connections."
  },
  {
    serialNo: 7,
    id: "PS7",
    origId: "PS11",
    title: "Timing Integrity for Distributed Observatories",
    track: "software",
    isHybrid: false,
    category: "Distributed Systems & DSP",
    difficulty: "HARD",
    overview: "Build a cooperative timing-integrity system that compares timestamps across distributed observing nodes and flags a node whose timing appears to be drifting or spoofed, before its data is trusted.",
    fullDetails: "Distributed telescopes rely on extremely accurate timestamps for events like stellar occultations; clock drift, camera delay, or GNSS interference/spoofing can silently corrupt otherwise valid observations. This project requires building a network of observing nodes that compares GNSS time, local clock time, camera-trigger timestamps, and RF time exchange between nodes, identifies a drifting or spoofed node, and assigns every observation a timing-confidence score."
  },
  {
    serialNo: 8,
    id: "PS8",
    origId: "PS7",
    title: "AEGIS-LINK: AI-Enabled Adaptive Anti-Jamming Communication System",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Signal Processing",
    difficulty: "HARD",
    overview: "Design and develop an AI-enabled adaptive communication system capable of detecting intentional or unintentional signal jamming and autonomously mitigating its effects. The system must identify interference patterns in real time and dynamically switch frequencies using intelligent frequency hopping techniques to ensure secure and uninterrupted communication.",
    fullDetails: "Wireless communication systems used in critical operations are vulnerable to signal jamming and interference. This project proposes an AI-driven anti-jamming framework that detects anomalous signal behavior and rapidly adapts transmission parameters to maintain reliable and secure communication using Software Defined Radio (SDR) for flexible spectrum control, FFT-based spectral analysis, ML-based classification of interference types, and adaptive frequency hopping within milliseconds.",
    hardwareReq: "SDR platform, RF antennas and transceiver modules, processing unit (embedded system or PC), encryption module / secure communication interface."
  },
  {
    serialNo: 9,
    id: "PS9",
    origId: "PS50",
    title: "Federated Learning Across IoT Devices",
    track: "software",
    isHybrid: false,
    category: "IoT & Distributed AI",
    difficulty: "HARD",
    overview: "Trains a machine-learning model across many IoT devices without sharing raw data (federated learning).",
    fullDetails: "Centralizing data from many IoT devices for training raises privacy and bandwidth concerns. This project requires implementing a federated learning system where each device trains a local model on its own data and only shares model updates, which are aggregated into a shared global model, without any raw data ever leaving the device."
  },
  {
    serialNo: 10,
    id: "PS10",
    origId: "PS57",
    title: "Local Real-Time Factory Sensor Anomaly Detection",
    track: "software",
    isHybrid: false,
    category: "Edge Computing & Industrial IoT",
    difficulty: "MEDIUM",
    overview: "Detects anomalies in factory sensor data locally and instantly, with no cloud round-trip.",
    fullDetails: "Sending every sensor reading to the cloud for anomaly detection introduces latency that is unacceptable on a factory floor where faults must be caught immediately. This project requires an on-device (edge) anomaly detection system that processes factory sensor streams locally and raises alerts instantly, without depending on a round trip to a cloud server."
  },
  {
    serialNo: 11,
    id: "PS11",
    origId: "PS60",
    title: "Disaster Coordination Web Platform",
    track: "software",
    isHybrid: false,
    category: "Web & Public Safety",
    difficulty: "EASY",
    overview: "A web platform for volunteers, authorities, and citizens to coordinate during a disaster.",
    fullDetails: "Disaster response is often hampered by poor coordination between citizens reporting needs, volunteers offering help, and authorities managing resources. This project requires building a web platform that brings these three groups together in one place, enabling requests, resource offers, and official updates to be shared and coordinated efficiently during a disaster."
  },
  {
    serialNo: 12,
    id: "PS12",
    origId: "PS69-DUP",
    title: "CareSync (Clinical Triage System)",
    track: "software",
    isHybrid: false,
    category: "AI & HealthTech",
    difficulty: "MEDIUM",
    overview: "A lightweight AI triage tool for clinics with poor internet connectivity and limited resources.",
    fullDetails: "This entry features a lightweight AI-driven triage tool designed to run with minimal connectivity and hardware requirements, helping clinic staff quickly assess patient urgency and prioritize care using whatever limited data and infrastructure is available."
  },
  {
    serialNo: 13,
    id: "PS13",
    origId: "PS9-NEW",
    title: "Predictive Network Degradation Protection",
    track: "software",
    isHybrid: false,
    category: "Cloud Systems & Resilience",
    difficulty: "MEDIUM",
    overview: "Predicts network degradation ahead of time and protects a time-critical cloud upload via checkpointing, prioritizing, or compressing data so it doesn't have to restart from zero.",
    fullDetails: "Rather than letting a time-critical cloud upload fail and restart from scratch when the network degrades, the system predicts the degradation in advance and preserves progress through checkpointing, prioritization of critical data, or compression of the remaining transfer."
  },
  {
    serialNo: 14,
    id: "PS14",
    origId: "PS12-NEW",
    title: "Conflict-Resolution Referee for Mobile Network Controllers",
    track: "software",
    isHybrid: false,
    category: "Mobile Networks & Simulation",
    difficulty: "MEDIUM",
    overview: "Simulates a mobile network where several automated controllers (energy, coverage, interference) can give contradictory orders to the same antenna; a referee system catches conflicts and approves, modifies, delays, or rejects each change.",
    fullDetails: "In a mobile network, multiple automated controllers may independently try to optimize for different goals — energy savings, coverage, interference — and can issue conflicting instructions to the same antenna at the same time. This project requires simulating such a multi-controller network and building a referee system that intercepts each proposed change, detects conflicts between controllers, and decides whether to approve, modify, delay, or reject the change to keep the network in a consistent state."
  },
  {
    serialNo: 15,
    id: "PS15",
    origId: "PS29",
    title: "Coverage Dead-Zone Heatmap Tool",
    track: "software",
    isHybrid: false,
    category: "Wireless & Signal Propagation",
    difficulty: "EASY",
    overview: "Take a tower's location and transmit power as input and generate a heatmap showing where signal coverage is weak or absent.",
    fullDetails: "Mobile network planners need a fast way to visualize coverage gaps without running a full field survey. This project requires modeling signal propagation (a simple path-loss model is enough) from a given tower's coordinates and power, then rendering the resulting coverage strength as a heatmap overlaid on a map."
  },
  {
    serialNo: 16,
    id: "PS16",
    origId: "PS8-SW",
    title: "Rural Coverage Gap Mapper",
    track: "software",
    isHybrid: false,
    category: "GIS & Telecom Planning",
    difficulty: "EASY",
    overview: "Identify underserved rural areas and suggest where new towers should be placed.",
    fullDetails: "Rural connectivity planning is often done manually and slowly. This project requires combining population/settlement data with existing tower coverage data to flag underserved regions, then suggesting candidate new tower sites that maximize population coverage gained per tower. (Note: Doable only with synthetic or open grid data — avoid depending on real census datasets that teams won't have time to source)."
  },
  {
    serialNo: 17,
    id: "PS17",
    origId: "PS73",
    title: "BER Prediction Using Machine Learning",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Signal Processing",
    difficulty: "EASY",
    overview: "Train an ML model to predict bit-error rate from communication-system parameters such as modulation type, SNR, bandwidth, and channel conditions.",
    fullDetails: "Estimating BER analytically gets complex fast as more real-world factors are added. This project trains a regression/classification model on simulated or synthetic communication-link data to predict BER directly from system parameters, giving a much faster estimate than a full analytical or simulation-based calculation."
  },
  {
    serialNo: 18,
    id: "PS18",
    origId: "PS30",
    title: "Antenna Gain/Bandwidth Predictor from Design Inputs",
    track: "software",
    isHybrid: false,
    category: "AI/ML & Antenna Engineering",
    difficulty: "MEDIUM",
    overview: "ML predicts an antenna's gain and bandwidth from its design inputs.",
    fullDetails: "Antenna design typically requires iterative electromagnetic simulation to determine gain and bandwidth for a given geometry. This project requires generating a dataset of antenna design parameters (e.g., patch dimensions, substrate properties, feed position) and their corresponding gain/bandwidth (from formulas or simulation), then training a model to predict gain and bandwidth directly from new design inputs, cutting down iteration time."
  },
  {
    serialNo: 19,
    id: "PS19",
    origId: "PS74",
    title: "Virtual IoT Device Emulator",
    track: "software",
    isHybrid: false,
    category: "IoT Simulation & Testing",
    difficulty: "MEDIUM",
    overview: "Create a configurable software environment capable of emulating hundreds of IoT devices, each producing realistic sensor data, failures, and communication events for testing IoT applications.",
    fullDetails: "Testing IoT applications at scale is hard without access to hundreds of physical devices. This project requires building an emulator that can spin up large numbers of virtual devices, each generating configurable sensor data streams, simulated failures, and network events, so downstream IoT applications can be tested realistically."
  },
  {
    serialNo: 20,
    id: "PS20",
    origId: "PS75",
    title: "Cooperative IoT Fault Localization",
    track: "software",
    isHybrid: false,
    category: "IoT Systems & Algorithms",
    difficulty: "HARD",
    overview: "Simulate an IoT network with multiple interacting sensors and develop an algorithm that identifies which device is most likely responsible when several sensors report abnormal readings.",
    fullDetails: "When several sensors in an IoT network report anomalies at once, it's often one faulty device causing correlated effects rather than several independent failures. This project requires simulating a network of interacting sensors and building an algorithm that traces correlated abnormal readings back to the most likely root-cause device."
  },
  {
    serialNo: 21,
    id: "PS21",
    origId: "PS76",
    title: "IoT Sensor Reliability Scoring System",
    track: "software",
    isHybrid: false,
    category: "IoT Data Quality Engine",
    difficulty: "MEDIUM",
    overview: "Create a reliability engine that continuously assigns a confidence score to each sensor based on historical accuracy, missing values, noise, drift, and agreement with neighboring sensors.",
    fullDetails: "Not all sensor readings deserve equal trust — some sensors drift or degrade over time. This project requires building a scoring engine that tracks each sensor's historical accuracy, missing-data rate, noise level, drift, and agreement with nearby sensors, and continuously updates a reliability score per sensor."
  },
  {
    serialNo: 22,
    id: "PS22",
    origId: "PS23",
    title: "On-Device Signal Drop / Handover Predictor",
    track: "software",
    isHybrid: false,
    category: "Mobile Systems & Edge AI",
    difficulty: "MEDIUM",
    overview: "An on-device model predicts signal drops and handovers before they happen.",
    fullDetails: "Signal drops and handover failures degrade user experience, especially for latency-sensitive apps. This project requires training a lightweight, on-device model that uses recent signal-quality trends to predict an upcoming drop or handover event slightly before it happens, so an application can prepare (e.g., pre-buffer, pre-fetch, or notify)."
  },
  {
    serialNo: 23,
    id: "PS23",
    origId: "PS66",
    title: "Acoustic Data Link — Sound-Based Data Transfer",
    track: "software",
    isHybrid: false,
    category: "Signal Processing & Audio",
    difficulty: "MEDIUM",
    overview: "Send data between two devices as sound (speaker to microphone) instead of Wi-Fi.",
    fullDetails: "In environments where Wi-Fi/Bluetooth is unavailable or restricted, audio can carry data between nearby devices. This project requires encoding data into an audio signal (e.g., via frequency-shift keying or similar), transmitting it through a speaker, and decoding it from a microphone on a receiving device, handling noise and synchronization."
  },
  {
    serialNo: 24,
    id: "PS24",
    origId: "PS64",
    title: "Deepfake Voice Detector for Live Calls",
    track: "software",
    isHybrid: false,
    category: "AI Speech & Security",
    difficulty: "MEDIUM",
    overview: "Detect AI-generated (deepfake) voices on live calls in real time and show a trust score.",
    fullDetails: "Voice-cloning scams are a growing threat on voice calls. This project requires analyzing live (or streamed) call audio for artifacts characteristic of synthetic speech and continuously updating a trust score displayed to the user during the call. (Note: Use a pretrained voice-spoofing detection backbone rather than training a deepfake detector from scratch)."
  },
  {
    serialNo: 25,
    id: "PS25",
    origId: "PS72",
    title: "Unauthorized Radio Signal Classifier",
    track: "software",
    isHybrid: false,
    category: "DSP & RF Spectrum Security",
    difficulty: "HARD",
    overview: "Classify captured radio signals and flag unknown or unauthorized transmissions.",
    fullDetails: "Spectrum monitoring needs to tell known, licensed signal types apart from rogue transmissions. This project requires building a classifier over captured (or SDR-simulated) RF signal data that recognizes known modulation/signal classes and flags anything that doesn't match as unknown or unauthorized. (Note: Scope to synthetic/simulated IQ signals)."
  },
  {
    serialNo: 26,
    id: "PS26",
    origId: "PS77",
    title: "Adaptive Equalizer for Wireless Channels",
    track: "software",
    isHybrid: false,
    category: "Signal Processing & Communications",
    difficulty: "HARD",
    overview: "Build a software simulator for a time-varying wireless channel and implement an adaptive equalizer that continuously updates its coefficients to compensate for channel distortion.",
    fullDetails: "Wireless channels distort signals in ways that change over time (multipath, fading), so a fixed equalizer isn't enough. This project requires simulating a time-varying channel and implementing an adaptive algorithm (e.g., LMS/RLS-based) that continuously adjusts equalizer coefficients to minimize distortion as channel conditions change."
  },

  // ==========================================
  // --- HARDWARE TRACK (PURE HARDWARE & HYBRID PROBLEMS) ---
  // ==========================================
  {
    serialNo: 1,
    id: "PS1-HW",
    origId: "PS1",
    title: "Autonomous Motorized Antenna Beam-Tracker",
    track: "hardware",
    isHybrid: false,
    category: "Embedded & Robotics",
    difficulty: "HARD",
    overview: "Build a closed-loop, 2-axis motorized tracking mount that autonomously points a directional antenna at a moving beacon to maintain maximum signal strength.",
    fullDetails: "High-gain directional antennas are essential for long-range links but fail if misaligned. This project requires constructing a servo-driven mechanical mount controlled by a microcontroller that continuously samples the Received Signal Strength Indicator (RSSI) from a mobile RF beacon and executes a gradient-ascent algorithm to maintain physical alignment."
  },
  {
    serialNo: 2,
    id: "PS2-HW",
    origId: "PS2",
    title: "Ground-Searching 'Foxhunt' Radio Direction Finder",
    track: "hardware",
    isHybrid: false,
    category: "RF Hardware & Rescue",
    difficulty: "MEDIUM",
    overview: "Design a handheld, ergonomic search-and-rescue direction finder that processes rapid RSSI fluctuations to guide an operator directly toward a hidden beacon (useful for avalanche/landslide rescue).",
    fullDetails: "Locating downed transmitters or emergency beacons requires translating invisible RF signals into human-readable directions. This project involves building a highly directional antenna wand coupled with a microcontroller that filters noisy RSSI data and provides real-time audiovisual feedback (pitch shifting or bar graphs) proportional to signal strength."
  },
  {
    serialNo: 3,
    id: "PS3-HW",
    origId: "PS3",
    title: "Sub-Terrestrial Soil Moisture Sensing via RF Attenuation",
    track: "hardware",
    isHybrid: false,
    category: "RF Sensors & Agriculture",
    difficulty: "MEDIUM",
    overview: "Build a non-invasive RF sensing chamber to demonstrate the monotonic relationship between microwave signal attenuation and soil moisture content.",
    fullDetails: "Traditional agricultural moisture sensors degrade rapidly due to galvanic corrosion. Because water has a high dielectric constant, it attenuates RF signals predictably. This project requires passing a Sub-GHz or 2.4 GHz signal through a soil chamber and calculating the volumetric water content entirely based on the measured physical signal loss."
  },
  {
    serialNo: 4,
    id: "PS4-HW",
    origId: "PS4",
    title: "Through-Wall Presence Detection Radar",
    track: "hardware",
    isHybrid: false,
    category: "Radar & Microwave Systems",
    difficulty: "HARD",
    overview: "Interrogate a drywall or plywood partition using a radar module to detect human presence and biological micro-movements without optical line-of-sight.",
    fullDetails: "Search and rescue or tactical operations require situational awareness through solid barriers. Because low-frequency microwaves penetrate standard building materials, this project requires calibrating an FMCW or CW radar to map the environment, filter out static wall reflections, and amplify the moving targets located on the other side."
  },
  {
    serialNo: 5,
    id: "PS5-HW",
    origId: "PS5",
    title: "Vehicular Platoon Anti-Collision Doppler Brake System",
    track: "hardware",
    isHybrid: false,
    category: "Automotive Radar & Control",
    difficulty: "HARD",
    overview: "Mount a Doppler radar on a mobile chassis to continuously measure relative velocity and automatically engage reverse thrust when a rapid negative velocity shift is detected.",
    fullDetails: "Autonomous vehicle platooning requires sub-second braking reflexes to prevent cascading collisions. This hardware challenge utilizes a continuous-wave Doppler radar to measure the frequency shift of a lead vehicle. If the lead vehicle brakes hard, the hardware must physically override the trailing vehicle's motor controller before impact."
  },
  {
    serialNo: 6,
    id: "PS6-HW",
    origId: "PS6",
    title: "Self-Healing Secure IoT Disaster Mesh Network (RESILINK GRID)",
    track: "hardware",
    isHybrid: true,
    category: "IoT Mesh & Emergency Comms",
    difficulty: "HARD",
    overview: "Design and develop a secure, self-healing IoT mesh network capable of sustaining reliable communication during disaster scenarios where conventional infrastructure has failed. The system must maintain data integrity, location awareness, and network continuity even in the presence of node failures or large-scale disruption.",
    fullDetails: "Natural disasters frequently disable centralized communication systems, isolating distributed IoT sensors that are critical for early warning and situational awareness. This project proposes a resilient mesh-based IoT communication framework that autonomously maintains connectivity and secures transmitted data across affected regions. Requirements: automatic mesh formation without manual configuration, self-healing routing to bypass failed/disconnected nodes, secure communication using encryption/authentication, real-time sensor data transmission, GPS location tagging, and resilience against partial network collapse.",
    hardwareReq: "ESP32 or similar IoT nodes, LoRa/WiFi mesh communication modules, GPS module, edge gateway device (Raspberry Pi or equivalent), power backup modules, monitoring workstation."
  },
  {
    serialNo: 7,
    id: "PS7-HW",
    origId: "PS8",
    title: "Adaptive Communication System for Disaster-Resilient Networks",
    track: "hardware",
    isHybrid: true,
    category: "Emergency Mesh & Hardware Nodes",
    difficulty: "MEDIUM",
    overview: "During natural disasters such as earthquakes, floods, or landslides, conventional communication infrastructure may become unavailable due to power failures, damaged towers, network congestion, or loss of backhaul connectivity. Develop a portable, self-configuring communication node capable of establishing and maintaining communication between users/devices in the absence of conventional cellular or internet infrastructure.",
    fullDetails: "During natural disasters such as earthquakes, floods, or landslides, conventional communication infrastructure may become unavailable. This project requires developing a portable, self-configuring communication node capable of establishing and maintaining communication between users/devices in the absence of conventional cellular or internet infrastructure."
  },
  {
    serialNo: 8,
    id: "PS8-HW",
    origId: "PS9",
    title: "TerraTrack — Road Anomaly Detection",
    track: "hardware",
    isHybrid: true,
    category: "Embedded Hardware & Accelerometers",
    difficulty: "MEDIUM",
    overview: "Current municipal infrastructure lacks a continuous, crowdsourced method for real-time road anomaly detection, leaving two-wheeler riders vulnerable to accidents and delaying critical SOS emergency responses. Build a system (typically accelerometer + GPS + connectivity module on a two-wheeler) that detects road anomalies such as potholes in real time, crowdsources this data, and can trigger SOS alerts for accident scenarios.",
    fullDetails: "Current municipal infrastructure lacks a continuous, crowdsourced method for real-time road anomaly detection. Build an IoT device (accelerometer + GPS + LTE/ESP32) mounted on vehicles that uses on-edge signal classification to detect potholes, map road anomalies, and automatically dispatch SOS alerts upon impact."
  },
  {
    serialNo: 9,
    id: "PS9-HW",
    origId: "PS10",
    title: "Intelligent Reconfigurable Wireless Device",
    track: "hardware",
    isHybrid: true,
    category: "Smart RF & Hardware Control",
    difficulty: "MEDIUM",
    overview: "Wireless devices often experience weak signals and interference when their surroundings or network conditions change. Propose a smart wireless device that can detect these changes and automatically adjust its communication settings (channel, power, modulation, etc.) to maintain a strong, reliable, and energy-efficient connection.",
    fullDetails: "Wireless devices experience fading and interference when surroundings change. Propose a smart wireless hardware node that continuously senses channel conditions and uses embedded decision logic to dynamically adjust modulation schemes, frequency channels, and transmit power."
  },
  {
    serialNo: 10,
    id: "PS10-HW",
    origId: "PS11",
    title: "ShieldLink: Autonomous Tactical Communication Relay Network",
    track: "hardware",
    isHybrid: true,
    category: "Defense Tech & Hardware Relays",
    difficulty: "HARD",
    overview: "Modern defense operations rely heavily on uninterrupted communication between soldiers, unmanned systems, and command centers operating in dynamic and communication-denied environments. Develop an autonomous tactical communication relay system capable of dynamically extending communication coverage, maintaining secure connectivity between distributed units, and adapting to changing operational conditions to ensure reliable battlefield communication in infrastructure-limited environments.",
    fullDetails: "Modern defense operations require uninterrupted connectivity across harsh terrain. Develop autonomous mobile/drone relay nodes that evaluate signal strength and dynamically reposition themselves to preserve high-bandwidth encrypted data links between squads and command centers."
  },
  {
    serialNo: 11,
    id: "PS11-HW",
    origId: "PS12",
    title: "Adaptive Emergency Drone Landing Beacon",
    track: "hardware",
    isHybrid: true,
    category: "UAV & Hardware Beacons",
    difficulty: "HARD",
    overview: "As autonomous drones become an integral part of smart cities and critical services, unexpected failures such as communication loss, GPS denial, or battery depletion pose significant safety risks. Design a smart landing assistance system capable of communicating with distressed drones, identifying safe landing zones, and enabling reliable emergency landings through adaptive wireless communication and intelligent decision-making.",
    fullDetails: "Drone failures in smart cities pose severe safety risks. Design an external smart landing beacon equipped with wireless transceivers and sensors that communicates with drones suffering from low battery or GPS denial, selecting a safe landing pad and guiding the drone down autonomously."
  },
  {
    serialNo: 12,
    id: "PS12-HW",
    origId: "PS13",
    title: "Low-Power Acoustic Wildlife Intrusion Detection System (FORESTGUARD AI)",
    track: "hardware",
    isHybrid: true,
    category: "Edge Hardware & Acoustic Sensors",
    difficulty: "HARD",
    overview: "Design and develop a low-power acoustic-based animal intrusion detection system capable of identifying wildlife movement in forest regions and transmitting alerts through a cellular remote sensing network. The system must utilize deep learning classification techniques to distinguish animal sounds from environmental noise while ensuring energy-efficient operation for remote deployment.",
    fullDetails: "Forest-edge communities and sensitive ecological zones require early detection of animal intrusion to prevent human-wildlife conflict and protect biodiversity. Requirements: continuous acoustic monitoring via low-power sensors, on-device DL classification, noise filtering to reduce false detections, cellular-based remote data transmission, solar-powered energy-efficient operation, real-time alert generation, and scalable deployment.",
    hardwareReq: "Low-power acoustic sensor (microphone array), edge AI processing unit (ESP32/Raspberry Pi/low-power MCU), cellular communication module (4G/LTE), solar power unit with battery backup, central monitoring dashboard."
  },
  {
    serialNo: 13,
    id: "PS13-HW",
    origId: "PS14",
    title: "Intelligent Wireless Coverage Analytics and Optimization System (COVERAGE-AI)",
    track: "hardware",
    isHybrid: true,
    category: "Robotics & Hardware Sensors",
    difficulty: "MEDIUM",
    overview: "Design and develop an AI-enabled wireless signal mapping system capable of measuring, analyzing, and visualizing signal strength distribution across a defined area. The system must identify weak coverage zones and recommend optimal transmitter or tower placement to enhance network performance.",
    fullDetails: "Efficient wireless network deployment requires accurate knowledge of signal strength distribution across an environment. This project proposes a mobile-node-based signal mapping framework that collects RSSI data across different locations and uses AI techniques to predict weak zones and optimize infrastructure placement. Requirements: real-time RSSI measurement and logging, mobility-enabled data collection (drone/AGV/manual), signal strength heatmap generation, AI-based prediction of weak coverage zones, and recommendation of optimal tower/repeater placement.",
    hardwareReq: "ESP32 with RSSI measurement capability, wireless communication module (WiFi/LoRa), mobile platform (drone, AGV, or manual mobility setup), laptop for data logging/visualization, power supply units."
  },
  {
    serialNo: 14,
    id: "PS14-HW",
    origId: "PS15",
    title: "Intelligent Secure Communication Monitoring and Anomaly Detection System (SECURE-SHIELD AI)",
    track: "hardware",
    isHybrid: true,
    category: "RF Hardware & Cybersecurity",
    difficulty: "MEDIUM",
    overview: "Design and develop an AI-enabled secure communication system capable of detecting anomalous behavior within a wireless network. The system must monitor communication patterns in real time and identify abnormal message frequency, unauthorized nodes, or suspicious transmission activity to enhance network security.",
    fullDetails: "Wireless communication networks are vulnerable to malicious nodes, abnormal traffic behavior, and unauthorized access. This project proposes an intelligent monitoring framework that applies machine learning techniques to detect irregular communication patterns and flag potential security threats in real time. Requirements: continuous monitoring of traffic patterns, detection of abnormal message frequency/transmission spikes, identification of unknown/unauthorized nodes, ML-based anomaly detection trained on normal behavior, and real-time alert generation.",
    hardwareReq: "ESP32 communication nodes, laptop or monitoring workstation, wireless communication modules (WiFi/LoRa/BLE), power supply units."
  },
  {
    serialNo: 15,
    id: "PS15-HW",
    origId: "PS16",
    title: "Intelligent Store-and-Forward Resilient Network System (DELAYSMART)",
    track: "hardware",
    isHybrid: true,
    category: "Delay-Tolerant Hardware & Storage",
    difficulty: "MEDIUM",
    overview: "Design and develop an AI-enabled delay-tolerant communication system capable of maintaining reliable data exchange in environments with intermittent or unstable connectivity. The system must intelligently predict optimal transmission windows, store data during network outages, and forward it once connectivity is restored.",
    fullDetails: "In remote regions, disaster zones, and space communication scenarios, continuous network connectivity cannot be guaranteed. This project proposes a delay-tolerant networking framework that uses intelligent prediction models and store-and-forward mechanisms to ensure reliable communication despite frequent disconnections. Requirements: detection of intermittent network availability, store-and-forward data mechanism during link failures, AI-based prediction of optimal transmission timing, simulation of network drops, reliable packet delivery despite high delay, and efficient memory/power management.",
    hardwareReq: "ESP32 communication nodes, local storage module (SD card or onboard flash), wireless communication modules (WiFi/LoRa), power supply units."
  },
  {
    serialNo: 16,
    id: "PS16-HW",
    origId: "PS17",
    title: "Communication-Aware Motion Safety",
    track: "hardware",
    isHybrid: false,
    category: "Robotics & RF Safety Control",
    difficulty: "HARD",
    overview: "Develop a system that predicts whether a planned movement of a remote-controlled vehicle will break the minimum communication link requirements — before the movement is executed — and takes preventive action.",
    fullDetails: "Remote-controlled heavy machinery loses control and video links when it turns behind terrain, crosses another machine, or enters an obstructed radio path, often triggering an emergency stop and a lengthy restart. This project requires building a scaled remote-vehicle system controlled by a microcontroller that combines location, direction, planned path, antenna measurements, and live network indicators (RSSI, latency, packet loss, video quality) to predict failure risk before the vehicle enters a communication shadow, and to trigger a preventive action such as switching antennas, changing route, or stopping safely."
  },
  {
    serialNo: 17,
    id: "PS17-HW",
    origId: "PS18",
    title: "Ground-Based GPS Backup",
    track: "hardware",
    isHybrid: false,
    category: "RF Positioning & Trilateration",
    difficulty: "MEDIUM",
    overview: "Build a ground-based positioning system that locates a person, vehicle, or device using nearby wireless stations when GPS is unavailable.",
    fullDetails: "GPS becomes weak or inaccurate indoors, between tall structures, or during disruptions. This project requires setting up three or more fixed wireless stations at known locations and a movable receiver controlled by a microcontroller (ESP32) that estimates its distance from each station and calculates its approximate position through trilateration, displaying it on a simple map in real time."
  },
  {
    serialNo: 18,
    id: "PS18-HW",
    origId: "PS19",
    title: "Self-Updating Radio Map for Hazardous Zones",
    track: "hardware",
    isHybrid: false,
    category: "Mobile Rovers & RF Mapping",
    difficulty: "HARD",
    overview: "Build a system that uses operational vehicles themselves to continuously update a site's radio coverage map and detect newly formed communication dead zones.",
    fullDetails: "Radio coverage maps in mines and construction zones go stale as terrain and machinery shift, and technicians often can't enter active risk zones to re-survey manually. This project requires mounting a rover or mobile communication node that records its position together with RSSI, latency, packet loss, and throughput, builds a continuously updated radio-quality map, detects when a new obstruction creates a weak region, and recommends a safer route or improved antenna/relay position."
  },
  {
    serialNo: 19,
    id: "PS19-HW",
    origId: "PS20",
    title: "Dual-Path Wireless Internet Continuity",
    track: "hardware",
    isHybrid: false,
    category: "Multi-Link Wireless Systems",
    difficulty: "MEDIUM",
    overview: "Develop a system that uses two wireless paths to keep a home's internet connection stable when one path becomes unreliable.",
    fullDetails: "Rural fixed-wireless broadband depends on a single radio link to a tower, which can weaken due to obstacles, terrain, or heavy traffic. This project requires setting up two ESP32 boards or Wi-Fi routers representing two independent towers feeding one receiver node representing a home, continuously checking the quality of both links, selecting the better one when one weakens, using both together when extra reliability is needed, and preserving an ongoing transfer during the switch."
  },
  {
    serialNo: 20,
    id: "PS20-HW",
    origId: "PS21",
    title: "Multi-Hop LoRa Mesh with Dynamic Congestion Avoidance for Underground Mining",
    track: "hardware",
    isHybrid: false,
    category: "Sub-GHz LoRa Mesh & Mining",
    difficulty: "HARD",
    overview: "Sub-surface mining tunnels suffer from extreme non-line-of-sight (NLOS) signal attenuation, high multipath reflections, and a lack of GPS timing, leading to network partitioning and high packet loss during emergencies. Design a decentralized, asynchronous mesh routing protocol over sub-GHz LoRa transceivers that dynamically optimizes link paths based on Received Signal Strength Indicator (RSSI) gradients, packet error rates, and channel hop counts, without relying on any centralized coordination or GPS timing.",
    fullDetails: "Sub-surface mining tunnels suffer from extreme non-line-of-sight (NLOS) signal attenuation, high multipath reflections, and a lack of GPS timing, leading to network partitioning and high packet loss during emergencies. Design a decentralized, asynchronous mesh routing protocol over sub-GHz LoRa transceivers that dynamically optimizes link paths based on Received Signal Strength Indicator (RSSI) gradients, packet error rates, and channel hop counts, without relying on any centralized coordination or GPS timing."
  },
  {
    serialNo: 21,
    id: "PS21-HW",
    origId: "PS22",
    title: "Non-Intrusive Pipeline Corrosion Monitor Using Guided Ultrasonic Waves",
    track: "hardware",
    isHybrid: false,
    category: "Ultrasonic Waves & EMAT Sensing",
    difficulty: "HARD",
    overview: "Buried and insulated chemical pipelines suffer from localized pitting and wall-thinning that conventional external point sensors fail to map across long spans. Build an intrinsically safe IoT sensor node driving low-power Electromagnetic Acoustic Transducers (EMAT) to excite guided Lamb waves along the pipe wall, running dispersion-curve analysis locally on the node to flag corrosion defects without requiring physical access to the pipe interior.",
    fullDetails: "Buried and insulated chemical pipelines suffer from localized pitting and wall-thinning that conventional external point sensors fail to map across long spans. Build an intrinsically safe IoT sensor node driving low-power Electromagnetic Acoustic Transducers (EMAT) to excite guided Lamb waves along the pipe wall, running dispersion-curve analysis locally on the node to flag corrosion defects without requiring physical access to the pipe interior."
  },
  {
    serialNo: 22,
    id: "PS22-HW",
    origId: "PS23",
    title: "Autonomous Water Reservoir Sludge Profiler with Depth-Integrated LPWAN",
    track: "hardware",
    isHybrid: false,
    category: "Underwater Sonar & LPWAN Robotics",
    difficulty: "HARD",
    overview: "Sediment buildup in municipal water tanks and settling ponds decreases storage capacity and contaminates drinking supply, yet mapping sludge depth usually requires manual dredging surveys. Design a floating, buoyancy-controlled robotic acoustic sensor node that periodically submerges, maps the multi-point sludge layer profile using high-frequency sonar, resurfaces, and transmits the resulting bathymetric matrix via LoRaWAN.",
    fullDetails: "Sediment buildup in municipal water tanks and settling ponds decreases storage capacity and contaminates drinking supply, yet mapping sludge depth usually requires manual dredging surveys. Design a floating, buoyancy-controlled robotic acoustic sensor node that periodically submerges, maps the multi-point sludge layer profile using high-frequency sonar, resurfaces, and transmits the resulting bathymetric matrix via LoRaWAN."
  },
  {
    serialNo: 23,
    id: "PS23-HW",
    origId: "PS24",
    title: "Multi-Gas Leak Triangulation System for Industrial Plants (GASTRACE)",
    track: "hardware",
    isHybrid: false,
    category: "Gas Sensor Grid & Localization",
    difficulty: "HARD",
    overview: "Most gas detectors only say a leak happened, not where. Build a distributed sensor grid that localizes the leak source from concentration patterns across nodes — like RSSI trilateration, but with diffusing gas instead of radio signal.",
    fullDetails: "This project requires deploying 4-6 gas sensor nodes (MQ-series or electrochemical sensors) on ESP32/STM32 microcontrollers, each performing calibrated gas sensing and sending time-synced readings over WiFi/BLE/LoRa to a central gateway (Raspberry Pi or laptop). The technical core is a localization algorithm — either weighted-centroid (source approximated as the concentration-weighted average of node positions), gradient-ascent (following rising concentration between neighboring nodes), or time-of-detection (triangulating from detection order/delay across nodes). The system must also filter basic false positives such as a drifting sensor versus an actual leak."
  },
  {
    serialNo: 24,
    id: "PS24-HW",
    origId: "PS25",
    title: "Noise-Pollution Mapping Network with Source Direction-Finding (SONOMAP)",
    track: "hardware",
    isHybrid: false,
    category: "Acoustic Arrays & Beamforming",
    difficulty: "HARD",
    overview: "Standard noise monitors just log dB levels. Build a network of nodes that also estimate the bearing to the dominant noise source at each location, using mic-array signal processing — turning scattered dB readings into an actual noise-source map.",
    fullDetails: "This project requires deploying 4-6 distributed nodes, each carrying a small microphone array (3-4 mics spaced a few cm apart) on an ESP32/Raspberry Pi, communicating over WiFi/LoRa to a central gateway. Each node must sample audio from its mic array and perform on-node direction-of-arrival (DOA) estimation — either time-difference-of-arrival (TDOA) between mic pairs via cross-correlation, or a beamforming (delay-and-sum) sweep to find the peak energy direction — alongside continuous dB level logging. A central dashboard overlays the dB heatmap with directional arrows per node (or a triangulated source point where two or more nodes agree) on a site map, with basic filtering to reject transient or irrelevant noise such as wind gusts or node self-noise."
  }
];
